version: "3.3"
services:
  kaldi:
    image: "mymodel"
  web:
    image: "danijel3/kaldi-webrtc"
    volumes:
      - ${PWD}/servers.json:/server/servers.json
    ports:
      - "8080:8080"
  ingress:
    image: nginx
    volumes:
      - ./nginxconf/:/etc/nginx/conf.d/
    ports:
      - 8000:8000
